### ISSUE TITLE
请问如何执行

### ISSUE THREAD

**Issue by findyy99** [specialdog/Text-Detection#1]
作者您好，请问您所说的执行，对于m后缀的文件是用Matlab这个软件执行吗？

**Comment by specialdog** [comment]
是的，用matlab执行
如果这个项目对你有用，方便的话可以给个star
---原始邮件---
发件人:"Echoo"<notifications@github.com>;
发送时间:2019年9月4日(星期三) 下午3:36
收件人:"specialdog/Text-Detection"<Text-Detection@noreply.github.com>;
抄送人:"Subscribed"<subscribed@noreply.github.com>;
主题:[specialdog/Text-Detection] 请问如何执行 (#1)


作者您好，请问您所说的执行，对于m后缀的文件是用Matlab这个软件执行吗？
 
&mdash;

**Comment by findyy99** [comment]
已star，请问有python或者其他语言版本的吗？或者查阅的网站分享的吗？十分感谢：）

**Comment by specialdog** [comment]
我之前参考了CSDN的一些代码，时间太久找不到是哪个了，而且用的算法太传统了效果不是很好。你是要复现什么论文吗？可以交流一下，我现在比较清闲，python不会，c++可以试着写写。




------------------ 原始邮件 ------------------
发件人: "Echoo"<notifications@github.com>;
发送时间: 2019年9月9日(星期一) 晚上6:49
收件人: "specialdog/Text-Detection"<Text-Detection@noreply.github.com>;
抄送: "特立独行的坤"<1372010965@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [specialdog/Text-Detection] 请问如何执行 (#1)




已star，请问有python或者其他语言版本的吗？或者查阅的网站分享的吗？十分感谢：）

**Comment by findyy99** [comment]
我不是想复现论文：），我是想拿来复现计算机研究与发展的一篇文章，链接在这儿http://crad.ict.ac.cn/CN/abstract/abstract3971.shtml，谢谢了：）

**Comment by findyy99** [comment]
作者您好，我想问下svm分类怎么跟mser 的链接起来呢，把mser边缘增强后的结果跟svm连起来

**Comment by specialdog** [comment]
要计算mser区域的相关特征，把特征向量输入你训练好的SVM分类器
---原始邮件---
发件人:"Echoo"<notifications@github.com>;
发送时间:2019年9月10日(星期二) 下午4:07
收件人:"specialdog/Text-Detection"<Text-Detection@noreply.github.com>;
抄送人:"specialdog"<1372010965@qq.com>;"Comment"<comment@noreply.github.com>;
主题:Re: [specialdog/Text-Detection] 请问如何执行 (#1)


作者您好，我想问下svm分类怎么跟mser 的链接起来呢，把mser边缘增强后的结果跟svm连起来
 
&mdash;

**Comment by anbn1** [comment]
sir can u plz provide training set images
